apiVersion: v1
kind: Service
metadata:
  name: hpgcpcluster
  labels:
    app: housepartyapp
    tier: hpgcpcluster
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      # nodePort: 30080
      targetPort: 30080
  selector:
    app: housepartyapp
    tier: hpgcpcluster
